### ISSUE TITLE
Pins cannot be downloaded after a couple days

### ISSUE THREAD

**Issue by unknownskl** [OpenXbox/xbox-smartglass-rest-python#11]
After a couple days the rest server cannot get the pins anymore. It looks like a refresh of the token is needed. See log file below:
> [2018-08-30 12:27:00,896] DEBUG in connectionpool: https://eplists.xboxlive.com:443 "GET /users/xuid(xxxxxxxxxxxxxxxx)/lists/PINS/XBLPins HTTP/1.1" 401 0
> [2018-08-30 12:27:00,903] ERROR in app: {'success': False, 'message': 'Download of pins failed, error: Expecting value: line 1 column 1 (char 0)'}
> 127.0.0.1 - - [2018-08-30 12:27:00] "GET /web/pins HTTP/1.1" 500 232 0.816191

Is it a good idea to refresh the token once a 401 status is received?

**Comment by hunterjm** [comment]
I saw this as well. I made a change in my component to auto check tokens on the refresh and not just when a console is on. Waiting to see if that helped. Too bad we can’t shorten the expiration for testing :)

**Comment by tuxuser** [comment]
@unknownskl is the problem solved?

**Comment by hunterjm** [comment]
@tuxuser - It is not.  Even though the tokens get refreshed successfully (as per the expiration dates when viewed via `/auth`), the web API that downloads pins still fails authentication after a day or two.

**Comment by tuxuser** [comment]
maybe not the refresh logic:

https://github.com/OpenXbox/xbox-smartglass-rest-python/blob/master/xbox/rest/app.py#L30

Changing from
```py
        if self.authentication_mgr.authenticated and not self._xbl_client:
            self._xbl_client = XboxLiveClient(
            ...
```
to
```py
        if self.authentication_mgr.authenticated:
            return self._xbl_client = XboxLiveClient(
            ...
```

might do the trick - otherways it will always return the *old* AuthenticationManager, holding the *old* tokens.
