### ISSUE TITLE
Question: Post regular login

### ISSUE THREAD

**Issue by foxriver76** [OpenXbox/xbox-smartglass-rest-python#12]
I'm trying out the rest server and wanted to login, but it seems I'm missing something. Tried it with a simple Browser based REST client with the following request: 
```json
curl -X POST -H 'Content-Type: application/json' -i http://localhost:5557/auth/login --data '
    {
         "email": "test@test.com",
         "password":"superSecret"
    }
```

But I'm getting the response:
```json
{"message":"No email or password parameter provided","success":false}
```

What I am missing here?

**Comment by unknownskl** [comment]
It's probably because you post it using json data. Can you try to do it using the urlencoded format? (See: https://gist.github.com/subfuzion/08c5d85437d5d4f00e5)

**Comment by foxriver76** [comment]
Of course. I thought it was JSON based, because responses are in JSON. :man_facepalming: 
Thank you.
