### ISSUE TITLE
Media status no longer works for bluray player or netflix after 0.9.3

### ISSUE THREAD

**Issue by dshokouhi** [OpenXbox/xbox-smartglass-rest-python#15]
I had to downgrade my xbox server and xbox one file to get the playing status to reflect properly.  It seems some changes were made that send a null media status.  Not sure why that was done but rolling back fixed it for me.

**Comment by unknownskl** [comment]
Did Netflix ever work? It never worked for me. Can you verify it worked before?

**Comment by dshokouhi** [comment]
@unknownskl yup netflix and bluray player both worked for me the very first time I tried this component.  After downgrading yesterday the media status is now coming in correctly for both of those apps.

**Comment by dshokouhi** [comment]
@unknownskl this is what I see on v 0.9.3 in home assistant which relies on /devices/<liveid>/media_status to be populated....it only populates on this version for me no matter how many times i restart on 0.9.4 and .5 it still does not reflect the status

![netflix-pause-xbox](https://user-images.githubusercontent.com/1634145/46038439-efd80b80-c0bf-11e8-9981-b2aa079ec2d5.png)
![netflix-play-xbox](https://user-images.githubusercontent.com/1634145/46038440-efd80b80-c0bf-11e8-944c-7d8e15eae2be.png)
![blu-ray-xbox-play-statusbar](https://user-images.githubusercontent.com/1634145/46038466-fd8d9100-c0bf-11e8-98a9-279896993122.png)

**Comment by tuxuser** [comment]
@dshokouhi Checked with latest REST server & hass addon - It reports Blu Ray Player status just fine - media progress and Start/Stop button is according to the media-state
