### ISSUE TITLE
Console info for LIVEID is not available

### ISSUE THREAD

**Issue by ilkeraktuna** [OpenXbox/xbox-smartglass-rest-python#17]
Hi,

I was able to connect to my 2 consoles last week with /device/LIVEID/connect  then power off by /device/LIVEID/poweroff

Now, when I try "connect" I get this response:

`{"message":"Console info for XXXXXXX is not available","success":false}`

However, I can see this when I get a list:

`{"devices":{"XXX1":{"address":"192.168.254.37","anonymous_connection_allowed":true,"authenticated_users_allowed":true,"connection_state":"Disconnected","console_users_allowed":false,"device_status":"Available","is_certificate_pending":false,"liveid":"XXX1","name":"XBOXONE1","pairing_state":"NotPaired","uuid":"e244169a-b443-26a2-15d9-823db57c68ee"},"XXX2":{"address":"192.168.254.38","anonymous_connection_allowed":true,"authenticated_users_allowed":true,"connection_state":"Disconnected","console_users_allowed":false,"device_status":"Available","is_certificate_pending":false,"liveid":"XXX2","name":"XBOXONE2","pairing_state":"NotPaired","uuid":"e1107115-1032-0e74-daae-488b4c9a092f"}},"success":true}`

Why can't I connect now ?

thanks

**Comment by tuxuser** [comment]
That looks odd, I have no way of verifying that right now.

**Comment by ilkeraktuna** [comment]
does anyone else have the same issue ?

**Comment by ilkeraktuna** [comment]
or anyone who does NOT have the issue with latest Xbox software/updates ?

**Comment by tuxuser** [comment]
Did you ensure capitalization on LIVEID?

**Comment by ilkeraktuna** [comment]
what do you mean by "capitalization on LIVEID" ?
I wrote it already in capital letters. And it was working until a few days ago when it suddenly stopped working. I have not changed anything.

**Comment by unknownskl** [comment]
Are you in the Xbox alpha/beta ring? For me it worked fine last Sunday after the update on the beta one.

**Comment by ilkeraktuna** [comment]
I don't know about the alpha/beta. How can I attend it ?
Was it not working for you before the update ?

**Comment by unknownskl** [comment]
You need to be xbox insider to attend the alpha or beta ring. But in case you don't, we can rule out it has something to do with the Xbox dashboard version. 

It is working fine for a couple weeks now for me on the beta ring. (Stable should be working fine as well)

**Comment by ilkeraktuna** [comment]
1.Are you authenticated with your user or do you connect anonymously?
Authenticated (and I loaded auth by /auth/load)

2.Does a restart of the xbox-smartglass-rest server fix the issue?
No.

3.Which Python version do you use?
I'm not sure. Let me check that when I'm home. But I did not change my Python version

4.Which package versions do you use? (Query /versions)
I'm not sure. I can write the exact version later when I'm home but I installed it a few weeks ago and did not change it since then. The problem did not exist around 1 week ago.

**Comment by unknownskl** [comment]
Thanks. Please let us know what versions you run once you are able to.
Please also try to logout and login again to see if that will fix this issue.

**Comment by ilkeraktuna** [comment]
I've also tried logout/login but that did not change the status.
I will post my Python and API versions later.

**Comment by ilkeraktuna** [comment]
Hi,

It is using python 3.5:

```
root@raspbx:~# ps -ef | grep xbox
root       754     1  0 Sep29 ?        00:10:12 /usr/bin/python /usr/local/bin/xbox-rest-server
root@raspbx:~# /usr/bin/python -V
Python 3.5.3
root@raspbx:~# 
```

Package version:
`{"success":true,"versions":{"xbox-smartglass-auxiliary":null,"xbox-smartglass-core":"1.0.10","xbox-smartglass-nano":null,"xbox-smartglass-rest":"0.9.5","xbox-smartglass-stump":"0.9.4","xbox-webapi":"1.1.5"}}

`

**Comment by tuxuser** [comment]
Change following line https://github.com/OpenXbox/xbox-smartglass-rest-python/blob/master/xbox/rest/decorators.py#L31

from
```
return app.error('Console info for {0} is not available'.format(liveid), HTTPStatus.FORBIDDEN)
```
to
```
return app.error('Console info for {0} is not available, ALL: {1}'.format(liveid, app.console_cache), HTTPStatus.FORBIDDEN)
```

Please post the output of:

`GET http://<rest-server-ip>:5557/device`
`GET http://<rest-server-ip>:5557/device/<LIVEID>`

**Comment by ilkeraktuna** [comment]
device/LIVEID output:

{"message":"Console info for FD001BB037A5BE11 is not available, ALL: {}","success":false}

device output:

{"devices":{"FD001BB037A5BE11":{"address":"192.168.254.37","anonymous_connection_allowed":true,"authenticated_users_allowed":true,"connection_state":"Disconnected","console_users_allowed":false,"device_status":"Available","is_certificate_pending":false,"liveid":"FD001BB037A5BE11","name":"XBOXONE1","pairing_state":"NotPaired","uuid":"e244569a-b443-26a2-15d9-823db57c11ee"}},"success":true}

**Comment by ilkeraktuna** [comment]
btw, I see many logs like below on the rest api console : 

[2018-10-03 23:06:39,430] DEBUG in protocol: Sending ConnectRequest to 192.168.254.38
[2018-10-03 23:06:39,438] DEBUG in protocol: Sending ConnectRequest to 192.168.254.38
[2018-10-03 23:06:39,446] DEBUG in protocol: Sending ConnectRequest to 192.168.254.38
<gevent._socket3.socket object, fd=15, family=2, type=2049, proto=0>: Invalid HTTP method: 'CNXN\x00\x00\x00\x01\x00\x00\x04\x00\x1b\x00\x00\x00M\n'                         " 400 - 0.001183
<gevent._socket3.socket object, fd=15, family=2, type=2049, proto=0>: Invalid HTTP method: 'CNXN\x00\x00\x00\x01\x00\x00\x04\x00\x1b\x00\x00\x00M\n'                         " 400 - 0.001174
[2018-10-03 23:06:41,414] DEBUG in protocol: Sending ConnectRequest to 192.168.254.37
[2018-10-03 23:06:41,422] DEBUG in protocol: Sending ConnectRequest to 192.168.254.37
[2018-10-03 23:06:41,430] DEBUG in protocol: Sending ConnectRequest to 192.168.254.37
<gevent._socket3.socket object, fd=15, family=2, type=2049, proto=0>: Invalid HTTP method: 'CNXN\x00\x00\x00\x01\x00\x00\x04\x00\x1b\x00\x00\x00M\n'                         " 400 - 0.001265
[2018-10-03 23:06:42,617] DEBUG in protocol: Sending ConnectRequest to 192.168.254.37
[2018-10-03 23:06:42,625] DEBUG in protocol: Sending ConnectRequest to 192.168.254.37
[2018-10-03 23:06:42,634] DEBUG in protocol: Sending ConnectRequest to 192.168.254.37
<gevent._socket3.socket object, fd=15, family=2, type=2049, proto=0>: Invalid HTTP method: 'CNXN\x00\x00\x00\x01\x00\x00\x04\x00\x1b\x00\x00\x00M\n'                         " 400 - 0.001693
<gevent._socket3.socket object, fd=15, family=2, type=2049, proto=0>: Invalid HTTP method: 'CNXN\x00\x00\x00\x01\x00\x00\x04\x00\x1b\x00\x00\x00M\n'                         " 400 - 0.001184
[2018-10-03 23:06:44,456] DEBUG in protocol: Sending ConnectRequest to 192.168.254.38
[2018-10-03 23:06:44,464] DEBUG in protocol: Sending ConnectRequest to 192.168.254.38
[2018-10-03 23:06:44,473] DEBUG in protocol: Sending ConnectRequest to 192.168.254.38
<gevent._socket3.socket object, fd=15, family=2, type=2049, proto=0>: Invalid HTTP method: 'CNXN\x00\x00\x00\x01\x00\x00\x04\x00\x1b\x00\x00\x00M\n'                         " 400 - 0.001210
<gevent._socket3.socket object, fd=15, family=2, type=2049, proto=0>: Invalid HTTP method: 'CNXN\x00\x00\x00\x01\x00\x00\x04\x00\x1b\x00\x00\x00M\n'                         " 400 - 0.001194
[2018-10-03 23:06:46,441] DEBUG in protocol: Sending ConnectRequest to 192.168.254.37
[2018-10-03 23:06:46,449] DEBUG in protocol: Sending ConnectRequest to 192.168.254.37
[2018-10-03 23:06:46,457] DEBUG in protocol: Sending ConnectRequest to 192.168.254.37
<gevent._socket3.socket object, fd=15, family=2, type=2049, proto=0>: Invalid HTTP method: 'CNXN\x00\x00\x00\x01\x00\x00\x04\x00\x1b\x00\x00\x00M\n'                         " 400 - 0.001320
[2018-10-03 23:06:47,644] DEBUG in protocol: Sending ConnectRequest to 192.168.254.37
[2018-10-03 23:06:47,652] DEBUG in protocol: Sending ConnectRequest to 192.168.254.37
[2018-10-03 23:06:47,660] DEBUG in protocol: Sending ConnectRequest to 192.168.254.37
<gevent._socket3.socket object, fd=15, family=2, type=2049, proto=0>: Invalid HTTP method: 'CNXN\x00\x00\x00\x01\x00\x00\x04\x00\x1b\x00\x00\x00M\n'                         " 400 - 0.002452
<gevent._socket3.socket object, fd=15, family=2, type=2049, proto=0>: Invalid HTTP method: 'CNXN\x00\x00\x00\x01\x00\x00\x04\x00\x1b\x00\x00\x00M\n'                         " 400 - 0.001186

**Comment by tuxuser** [comment]
1. There is a client trying to send invalid data to your server the REST server is running on.
2. For the sake of it, cannot reproduce your problem, sorry

**Comment by ilkeraktuna** [comment]
1. how can I trace it ? The rest server is just using the port 5557 , so when I get a tcpdump on this port , I only see local traffic:
00:06:48.870563 IP 127.0.0.1.59658 > 127.0.0.1.5557
then what is the invalid packet ?

2. how can I troubleshoot further ?
when I trun on the console manually , I get output on /device as : 

{"devices":{"FD001BB037A5BE11":{"address":"192.168.254.37","anonymous_connection_allowed":true,"authenticated_users_allowed":true,"connection_state":"Disconnected","console_users_allowed":false,"device_status":"Available","is_certificate_pending":false,"liveid":"FD001BB037A5BE11","name":"XBOXONE1","pairing_state":"NotPaired","uuid":"e244569a-b443-26a2-15d9-823db57c11ee"}},"success":true}

it says "notpaired" is that normal ?

**Comment by tuxuser** [comment]
Easiest way to get a more direct communication flow: Join our discord server, link is in the README

**Comment by tuxuser** [comment]
There were 3 problems that we troubleshot:

1. ADB daemon (Android debug bridge) was running in a script in the background, somehow seeing port 5557 as an android device - so it sent invalid packets to the REST server. Odd...
2. You have to run `/device` to scan for console before you call `/device/<LIVEID>` or `/device/<LIVEID>/connect`
3. If console does not respond to the `connect` command, power cycle the console by pressing the console's power button for 10 seconds to shut it down entirely, then start it again. After it booted, it will likely accept the connection.

I will create a FAQ for these.

**Comment by ilkeraktuna** [comment]
thanks
