### ISSUE TITLE
Cannot seem to login with the rest server

### ISSUE THREAD

**Issue by ShadowEO** [OpenXbox/xbox-smartglass-rest-python#18]
Log: https://gist.github.com/ShadowEO/4f0ebdd40ee7d30c67a97b26deb7535f
(I had it embedded directly into this report, but it formatted it badly)

Receiving this when I attempt /auth/login, when I use /auth/oauth it gives me

`Error Message: 'usr'`

Looks like this is a great project for providing programmable access to the Xbox One's functions, I hope that it's something that can be fixed pretty easily. Would love to use this with Home Assistant (I tried the addon as well, same result)

**Comment by Dark4Codrutz** [comment]
Can't reproduce, sorry!
Works fine for me with no 2FA
the first line in that log: did you used POST method ? I wasn't able to test that (don't know curl xD )

**Comment by ShadowEO** [comment]
I did not use POST unless the /auth/login or /auth/oauth endpoints do. I was attempting to authenticate using the existing web UI. I also have 2FA disabled.

**Comment by tuxuser** [comment]
@ShadowEO same here, verified both endpoints, `/auth/login` and `/auth/oauth` - both are working fine for me, `/auth/oauth` is even fine with 2FA-enabled account.

**Comment by ShadowEO** [comment]
Odd, I wonder what's different with my setup that could be causing the problem. 0-0; Any ideas on what I could do to troubleshoot? (I had tried with both 2FA on and off, I had it on first, then turned it off when I thought maybe that was the reason for the problem)

**Comment by tuxuser** [comment]
Could you paste an obfuscated version (bogus access / refresh / user_id section) of your redirect URI that you get after authenticating?

**Comment by ShadowEO** [comment]
This is the URL that shows up in the address bar after authenticating:

https://login.live.com/oauth20_desktop.srf?lc=1033#access_token=bogus_token_here&token_type=bearer&expires_in=86400&scope=service::user.auth.xboxlive.com::MBI_SSL&refresh_token=bogus-refresh&user_id=bogus-uid

**Comment by tuxuser** [comment]
that looks fine to me - so something at the stage of XSTS auth is going nuts.

Please change the following in `xbox/webapi/common/userinfo.py`, then reinstall the edited code via `pip install .` inside the webapi root folder:

```py
return cls(node['xid'], node['uhs'], node['gtg'], node['agg'], node['prv'], node['usr'])
```

```py
return cls(
    node.get('xid'),
    node.get('uhs'),
    node.get('gtg'),
    node.get('agg'),
    node.get('prv'),
    node.get('usr')
)
```

**Comment by ShadowEO** [comment]
That worked! I received login succeeded after making the change.

**Comment by tuxuser** [comment]
@ShadowEO Could you post the output of `/auth` now, to see what your specific XSTS data is not holding - of course modifying the real-data.

**Comment by ShadowEO** [comment]
https://gist.github.com/ShadowEO/2fa31470903096df1ce823057e502a28

Here you are! If you'd like me to post it another way, let me know and I'll post it anyway you need. (I'm fine with my Gamertag being in there, all good!)
