### ISSUE TITLE
GameDVR endpoint throws error

### ISSUE THREAD

**Issue by foxriver76** [OpenXbox/xbox-smartglass-rest-python#25]
When trying to use the game dvr endpoint, I receive the following error as response: 

```json
{"message":"GameDVR failed, error: 'Console' object has no attribute 'game_dvr_record'","success":false}
```

Endpoint should record last 60 seconds (https://github.com/OpenXbox/xbox-smartglass-rest-python/blob/013e248502c95845a016a23b3a83331acfb1b233/xbox/rest/routes/device.py#L264). Am I missing something here?

**Comment by tuxuser** [comment]
Fixed with commit 9ec5b2f Pin xbox-smartglass-core requirement

The addition of game_dvr_record in Console-class was not versioned / pushed to PyPi.
