### ISSUE TITLE
Can't run docker file?

### ISSUE THREAD

**Issue by sofakng** [OpenXbox/xbox-smartglass-rest-python#27]
I've just installed the latest docker file from openxbox/xbox-smartglass-rest, but when I try to start the container I get an error:

`Traceback (most recent call last):
  File "/usr/local/bin/xbox-rest-server", line 7, in <module>
    from xbox.rest.scripts.rest_server import main
  File "/usr/local/lib/python3.6/site-packages/xbox/rest/scripts/rest_server.py", line 3, in <module>
    from gevent import wsgi
ImportError: cannot import name 'wsgi'
`

I'm running Docker version 18.06.1-ce, build e68fc7a on Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u5 (2018-09-30) x86_64 GNU/Linux.

**Comment by alexhardwicke** [comment]
Seems to be an issue with the tagged Latest build (looks like it failed to build so pulling Latest gives you 0.9.7 and this was solved in 0.9.8).

If you explicitly pull the build tagged v0.9.8 it seems to work.

**Comment by tuxuser** [comment]
The *latest" image is rebuilt now

**Comment by alexhardwicke** [comment]
Can confirm that (after manually removing the 0.9.8 tagged image) latest is working and is using pywsgi.
