### ISSUE TITLE
Is the magic packet possible when the xbox power brick light is orange? 

### ISSUE THREAD

**Issue by dalanmiller** [OpenXbox/xbox-smartglass-rest-python#33]
Hey all,

I've noticed that the magic 'power on' packet only works when my xbox after being plugged in, has been turned on, and then turned off. 

If I were to plug the xbox in to power, the power brick light would come on as orange. After being powered on, and then powered off, the power brick light would then remain white. It's only in this state that I'm observing that the power on signal will actually work. 

Has anyone else experienced the same or different?

**Comment by tuxuser** [comment]
Expected behaviour.
Console has to be in standby to receive poweron packet.
StandBy == White powerbrick LED
