### ISSUE TITLE
Xbox on different subnet

### ISSUE THREAD

**Issue by williamson10** [OpenXbox/xbox-smartglass-rest-python#35]
I can't seem to make this work across subnets. I have tried the url 
`host:5557/device?addr=x.x.x.x`
and get 
`{"devices":{},"success":true}` 
back.

If I move the xbox to the same subnet, I can connect although I still need to use the addr parameter. 

My subnet is a different vlan and does have a firewall between them. I don't see any dropped packets in the logs. What ports do I need open to make this work?

**Comment by tuxuser** [comment]
You need to make sure multicast is coming through.

@hunterjm As you are running a similar configuration, can you give a hint?

**Comment by williamson10** [comment]
I took a packet capture from the interface that the xbox is behind. I can see my server probe the xbox and the xbox does some multicast member querying but that is as far as it gets. On the interface the server is running behind, I get nothing.

![image](https://user-images.githubusercontent.com/16584557/63188481-7e82ad80-c02f-11e9-901f-b153f1845382.png)

**Comment by williamson10** [comment]
I just ended up adding another NIC to my server and joining it to that VLAN. Seems to work as expected now.
